# Generated by Django 4.2.9 on 2024-01-24 05:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('trdate', models.DateField()),
                ('fromplace', models.CharField(max_length=50)),
                ('toplace', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tbltransaction',
            },
        ),
    ]
