# Generated by Django 4.2.9 on 2024-01-24 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='tbltransaction_1',
        ),
    ]
