# Generated by Django 4.2.9 on 2024-01-24 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passes',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='passes',
            name='contact',
        ),
        migrations.AddField(
            model_name='passes',
            name='passtype',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
