# Generated by Django 4.2.9 on 2024-01-24 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0002_remove_passes_amount_remove_passes_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='passes',
            table='tblpass',
        ),
    ]
