# Generated by Django 4.2.9 on 2024-01-24 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0004_alter_passes_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='passes',
            table='tblpasses_1',
        ),
    ]
